### PR TITLE
Update to Factorio 2.0

### PR DESCRIPTION
**Pull request by SunSerega**
Icons no longer need this whole process. Now, you just copy a single path string.
Otherwise, everything is fine.

This was changed while updating the blueprint reader mod. PR for it is the main one. Will link from there in a second.

### CODE REVIEW

**Comment by SunSerega** [comment]
Here is why icons module is no longer needed:
https://github.com/IlRomanenko/FactorioBlueprintReader/pull/1/files#diff-3159c3a7a5943e2a2302031509a4eefe6ebf9340ad199d2f7b8797ebef0a4ce9R20

**Comment by raiguard** [comment]
`icons` still exists on prototypes, and well-made mods should check for both. Also, recipes can still infer their icon from their main product.

That said, I am re-implementing many of this mod's functions into the [Factorio Library](https://mods.factorio.com/mod/flib) which will be included in the next release.

**Comment by SunSerega** [comment]
> `icons` still exists on prototypes, and well-made mods should check for both

Ah, I see: https://lua-api.factorio.com/stable/prototypes/EntityPrototype.html#icons

But I guess it should matter in the case of the blueprint reader...

**Comment by theRustyKnife** [comment]
> `icons` still exists on prototypes, and well-made mods should check for both. Also, recipes can still infer their icon from their main product.

^ this

> That said, I am re-implementing many of this mod's functions into the [Factorio Library](https://mods.factorio.com/mod/flib) which will be included in the next release.

Please do, i really dont feel like checking if everything is still up to date :upside_down_face: Also if you do, it'd be great if you could let me know so i can mention it on here somewhere.

**Comment by SunSerega** [comment]
Alright, but I don't want to reimplement a mod using `rusty-locale` to use `flib`, so some things would still be left hanging...
I marked the blueprint reader PR as draft, and will close this one, since `rusty-locale` is being officially consumed by `flib`.

**Comment by theRustyKnife** [comment]
I suppose if the api ends up being significantly different i could make a new version of this that just wraps flib to make the migration easier. Or something like that. Either way, i assume raiguard will probably have it done before i could reasonably do anything here anyway, so it's not like you'd be waiting any less unfortunately.

**Comment by SunSerega** [comment]
Yeah, I understand, and it's not really a problem. In the first place, the quality of my 2.0 updates is subpar. They are mainly for myself, and I've only posted them to 1) let other people use at least something if they, like me, want to use the mod in 2.0 without waiting and 2) to get notifications for info like this, on what's the original mod author's plan.

**Pull request closed without merging**
